apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ticketing-system
data:
  DB_URL: "jdbc:mysql://mysql-service:3306/test"
  REDIS_HOST: "redis-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ticketing-system
type: Opaque
data:
  # base64 encoded 'root' and 'admin1234'
  DB_USERNAME: cm9vdA== 
  DB_PASSWORD: YWRtaW4xMjM0
